= API Gateway Monitoring
:!toc-title:
:!toc-placement:
:toc:

Monitor API Gateway for high integration latency and 5xx errors.

toc::[]

== Usage

Remember to check out the link:variables.tf[*variables*] to see all options.

IMPORTANT: Remember to add Datadog as a integration in your Slack channel! You also need to integrate Datadog with your AWS account.

Example with default variables.
[source, hcl]
----
module "datadog_monitor_api_gateway" {
  source               = "github.com/nsbno/terraform-datadog-monitors//modules/api_gateway?ref=x.y.z"
  service_display_name = "Infrademo Demo App"

  slack_channel_to_notify = "tmp-test-slack"
  api_name                = "infrademo-api"
}
----

Example where you can configure variables.
[source, hcl]
----
module "datadog_monitor_api_gateway" {
  source               = "github.com/nsbno/terraform-datadog-monitors//modules/api_gateway?ref=x.y.z"
  service_display_name = "Infrademo Demo App"

  slack_channel_to_notify = "tmp-test-slack"
  api_name                = "infrademo-api"

  error_5xx_period    = "15m"
  error_5xx_threshold = 10

  latency_evaluation_period = "15m"
  latency_alert_threshold   = 1000

  # If you want to use your team's own workflow
  workflow_to_attach = "@workflow-notify-slack-of-monitor-event"
}
----

== Relevant Repositories

You can use these repos together with this repo!

link:https://github.com/nsbno/terraform-datadog-service[`nsbno/terraform-datadog-service`]::
Connect a DataDog service to a team with metadata.

link:https://github.com/nsbno/terraform-aws-ecs-service[`nsbno/terraform-aws-ecs-service`]::
Connect an AWS ECS service to Datadog.

link:https://github.com/nsbno/terraform-aws-lambda[`nsbno/terraform-aws-lambda`]::
Connect an AWS Lambda function to Datadog.

link:github.com/nsbno/terraform-datadog-aws-integration[`nsbno/terraform-datadog-aws-integration`]::
Connect an AWS account to Datadog.
