= Lambda Errors Monitor
:!toc-title:
:!toc-placement:
:toc:

Monitor for AWS Lambda function invocation errors.

toc::[]

== Description

Monitors the `aws.lambda.errors` metric from Datadog's AWS integration, which tracks failed Lambda invocations.

Use this monitor to detect when Lambda functions are failing, enabling quick response to runtime errors, timeouts, or other issues affecting serverless workloads.

== Usage

Remember to check out the link:variables.tf[*variables*] to see all options.

IMPORTANT: Remember to add Datadog as a integration in your Slack channel! You also need to integrate Datadog with your AWS account.

Example with default variables.
[source, hcl]
----
// Prerequisites:
module "metadata" {
  source = "github.com/nsbno/terraform-aws-account-metadata?ref=x.y.z"
}

module "lambda_function" {
  source = "github.com/nsbno/terraform-aws-lambda?ref=x.y.z"
  [...]
}

module "datadog_lambda_errors" {
  source = "github.com/nsbno/terraform-datadog-monitors//modules/lambda_errors?ref=x.y.z"

  service_name  = "my-service"
  function_name = module.lambda_function.function_name

  # channel name only, e.g. tmp-test-slack
  slack_channel_to_notify = "tmp-test-slack"
}
----

Example where you can configure variables.
[source, hcl]
----
// Prerequisites:
module "metadata" {
  source = "github.com/nsbno/terraform-aws-account-metadata?ref=x.y.z"
}

module "lambda_function" {
  source = "github.com/nsbno/terraform-aws-lambda?ref=x.y.z"
  [...]
}

module "datadog_lambda_errors" {
  source = "github.com/nsbno/terraform-datadog-monitors//modules/lambda_errors?ref=x.y.z"

  service_name         = "my-service"
  service_display_name = "My Service"
  function_name        = module.lambda_function.function_name

  threshold = 5
  period    = "10m"

  # If you want to use your team's own workflow
  workflow_to_attach = "@workflow-notify-slack-of-monitor-event"
}
----

== Relevant Repositories

You can use these repos together with this repo!

link:https://github.com/nsbno/terraform-datadog-service[`nsbno/terraform-datadog-service`]::
Connect a DataDog service to a team with metadata.

link:https://github.com/nsbno/terraform-aws-ecs-service[`nsbno/terraform-aws-ecs-service`]::
Connect an AWS ECS service to Datadog.

link:https://github.com/nsbno/terraform-aws-lambda[`nsbno/terraform-aws-lambda`]::
Connect an AWS Lambda function to Datadog.

link:github.com/nsbno/terraform-datadog-aws-integration[`nsbno/terraform-datadog-aws-integration`]::
Connect an AWS account to Datadog.
